config/routes.rb
LearnRails::Application.routes.draw do
  resources :contacts, only: [:new, :create]
  resources :visitors, only: [:new, :create]
  resources :vklikers, only: [:new]
  root :to => 'visitors#new'
end

app/models/contact.rb
# Contact Class definition
class Contact < ActiveRecord::Base
  has_no_table
  column :name, :string
  column :email, :string
  column :content, :string
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :content
  validates_format_of :email, with:
  /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, maximum: 500

  def update_spreadsheet
    connection = GoogleDrive.login(ENV['GMAIL_USERNAME'],
                                   ENV['GMAIL_PASSWORD'])
    ss = connection.spreadsheet_by_title('Learn-Rails-Example')
    ss = connection.create_spreadsheet('Learn-Rails-Example') if ss.nil?
    ws = ss.worksheets[0]
    last_row = 1 + ws.num_rows
    ws[last_row, 1] = Time.new
    ws[last_row, 2] = @name
    ws[last_row, 3] = @email
    ws[last_row, 4] = @content
    ws.save
  end

end

app/models/visitor.rb
# Visitor Model Class
class Visitor < ActiveRecord::Base
  has_no_table
  column :email, :string
  validates_presence_of :email
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  def subscribe
    mailchimp = Gibbon::API.new
    result = mailchimp.lists.subscribe(
      id: ENV['MAILCHIMP_LIST_ID'],
      email: {email: @email},
      double_optin: false,
      update_existing: true,
      send_welcome: true
      )
    Rails.logger.info("Subscribed #{@email} to MailChimp") if result
  end
end

app/models/vkliker.rb
# vkliker model class
class Vkliker < ActiveRecord::Base
  # set_primary_key 'id'
  attr_reader :name, :id, :on
  has_no_table
  column :id, :integer
  column :on, :boolean
  column :name, :string
  validates_presence_of :id

  def initialize( id , name = 'Mr. Smith' , on = false)
    @id = id
    @name = name
    @on = on
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/vklikers_controller.rb
# Vkliker Controller Class definition
class VklikersController < ApplicationController

  def new
    @vkliker = Vkliker.new(123_456)
  end

end

app/controllers/contacts_controller.rb
# Contacts Controller Class definition
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    Rails.logger.debug "DEBUG: params are #{params}"
    @contact = Contact.new(secure_params)
    if @contact.valid?
      @contact.update_spreadsheet
      UserMailer.contact_email(@contact).deliver
      flash[:notice] = "Message sent from #{@contact.name}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def secure_params
    params.require(:contact).permit(:name, :email, :content)
  end
end

app/controllers/visitors_controller.rb
# Visitors Controller Class
class VisitorsController < ApplicationController
  def new
    @visitor = Visitor.new
  end

  def create
    @visitor = Visitor.new(secure_params)
    if @visitor.valid?
      @visitor.subscribe
      flash[:notice] = "Signed up #{@visitor.email}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def secure_params
    params.require(:visitor).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.haml
- content_for :title do
  Contact me
%h1.text-center Write me something
.col-md-6 
  %i{class: "fa fa-envelope-o fa-5", style: "font-size: 20em; padding: 2% 23%; color: #FF7C7C; text-shadow: 7px 2px 2px #9B9B9B;"}
.col-md-6
  = simple_form_for @contact, :html => { :class => 'form-horizontal', :style => "padding: 10% 10% 10% 0; " } do |form|
    = form.error_notification
    .form-group
      = form.input :name, autofocus: true, :input_html => { :class => "form-control" }, label: false, placeholder: "name"
    .form-group
      = form.input :email, :wrapper => :prepend, :input_html => { :class => "form-control" }, label: false, placeholder: "e-mail"
    .form-group
      = form.input :content, as: :text, :input_html => { :class => "form-control" }, label: false, placeholder: "message"
    .form-group
      = form.button :submit, 'Send message', class: 'btn btn-primary col-md-12'
%h1.text-center ...or stay updated
.col-md-6

app/views/layouts/_messages.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %a{:class => "close", "data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.haml
%ul.nav.navbar-nav
  %li= link_to 'Home', root_path
  %li= link_to 'About', page_path('about')
  %li= link_to 'Contact', new_contact_path
  %li= link_to 'Subscribe', new_visitor_path
  %li= link_to 'VkLiker', new_vkliker_path

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : "Max's Sandbox"
    %meta{:name => "description", :content =>"= content_for ? (:description) ? yield(:description) : \"Learning Rails\""}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header{:class => "navbar-inverse navbar-fixed-top", :role => "navigatioin"}
      .container
        .navbar-header
          %a{:href => "/", :class => "navbar-brand"} Learn Rails
        = render 'layouts/navigation'
    %main{:role => "main"}
      .container
        .content
          .row
            .col-md-12
              = render 'layouts/messages'
              = yield
        %footer
          %p.text-center
            2013-#{Date.today.year} © Max Pogorelov
            

app/views/pages/about.haml
- content_for :title do
  About Max Pogorelov
%h3 About Max Pogorelov
%p
  He was born in Kharkov, Ukraine. He left New Zealand for England, excelled
  at the University of Mopery, and served in the Royal Loamshire Regiment. While in
  service, he invented the kanuten valve used in the processing of unobtainium for
  industrial use. He founded Acme Manfacturing, later acquired by the Advent Corporation,
  to commercialize the product. Mr. Kadigan is now retired and lives in Middlehampton
  where he raises Griadium frieda.
%p His favorite quotation is:
%p
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
  incididunt ut labore et dolore magna aliqua.

app/views/visitors/new.haml
- content_for :title do
  Subscribe for news

%h1.text-center Stay up to date
.col-md-6
  = simple_form_for @visitor, :html => { :class => 'form-horizontal', :style => "padding: 20% 10% 10% 18%" } do |f|
    = f.error_notification
    .form-group
      = f.input :email, label: false, :placeholder => 'Your email address...', :input_html => { :class => "form-control"}
    .form-group
      = f.submit "Sign up for the newsletter", :class => "btn btn-primary col-md-12"
.col-md-6 
  %i{class: "fa fa-hand-o-left fa-5", style: "font-size: 20em; padding: 2% 23%; color: #FF7C7C; text-shadow: 7px 2px 2px #9B9B9B;"}

app/views/vklikers/new.haml
- content_for :title do
  VKliker - automatic likes and promo in Vk

%h1 Hi, my name is #{@vkliker.name}
%p my ID: #{@vkliker.id} and I'm currently #{@vkliker.on ? 'on':'off'}